# Generated by Django 4.1.7 on 2023-05-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_myprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='skills',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='specification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
