# Generated by Django 4.1.7 on 2023-05-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(related_name='tasks', to='restapp.comment'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
