# Generated by Django 4.1.7 on 2023-05-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0007_task_comments_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
