# Generated by Django 4.1.7 on 2023-05-24 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0009_remove_comment_user_name_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
