# Generated by Django 4.1.7 on 2023-05-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0015_rename_content_comment_user_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_user',
            name='user',
        ),
    ]
