# Generated by Django 4.1.7 on 2023-06-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0019_project_myprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='myprofile',
            new_name='myprofile_id',
        ),
    ]
