# Generated by Django 4.1.7 on 2023-06-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0020_rename_myprofile_project_myprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
