# Generated by Django 4.2.2 on 2023-06-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0021_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('skills', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('Total_exp', models.IntegerField()),
                ('relevant_exp', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('current_ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notice_period', models.IntegerField()),
                ('feedback', models.TextField()),
            ],
        ),
    ]
