# Generated by Django 4.2.2 on 2023-06-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0023_remove_comment_user_comment_receiver_comment_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapp.users'),
        ),
    ]
