# Generated by Django 4.2.2 on 2023-06-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0024_myprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofile',
            old_name='user',
            new_name='user_id',
        ),
    ]
