# Generated by Django 4.2.2 on 2023-06-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0025_rename_user_myprofile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='receiver',
            new_name='receiver_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='sender',
            new_name='sender_id',
        ),
    ]
