# Generated by Django 4.2.2 on 2023-06-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0026_rename_receiver_comment_receiver_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('source_of_enquiry', models.CharField(max_length=255)),
                ('contacted_date', models.DateField(blank=True, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('comments', models.TextField()),
                ('personal_details', models.TextField()),
                ('handled_by', models.CharField(max_length=255)),
                ('office_visit', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=255)),
                ('feed_back', models.TextField()),
            ],
        ),
    ]
