# Generated by Django 4.2.2 on 2023-06-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0027_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qa',
            old_name='current_ctc',
            new_name='c_ctc',
        ),
        migrations.RenameField(
            model_name='qa',
            old_name='expected_ctc',
            new_name='e_ctc',
        ),
        migrations.RenameField(
            model_name='qa',
            old_name='Total_exp',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='qa',
            old_name='candidate_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='qa',
            old_name='mobile_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='qa',
            old_name='notice_period',
            new_name='period',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
