# Generated by Django 4.2.2 on 2023-06-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0029_rename_domain_qa_domain_rename_email_id_qa_email_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qa',
            old_name='c_ctc',
            new_name='Currentctc',
        ),
        migrations.RenameField(
            model_name='qa',
            old_name='Email_id',
            new_name='Emailid',
        ),
        migrations.RenameField(
            model_name='qa',
            old_name='e_ctc',
            new_name='Expectedctc',
        ),
        migrations.RenameField(
            model_name='qa',
            old_name='Relevant_exp',
            new_name='Relevantexperience',
        ),
    ]
