# Generated by Django 4.2.2 on 2023-06-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0030_rename_c_ctc_qa_currentctc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='comments',
            new_name='Comments',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='contacted_date',
            new_name='Contacteddate',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='feed_back',
            new_name='Feedback',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='followup_date',
            new_name='Followupdate',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='handled_by',
            new_name='Handledby',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='contact_number',
            new_name='Number',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='office_visit',
            new_name='Officevisit',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='personal_details',
            new_name='Personaldetails',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='source_of_enquiry',
            new_name='Sourceofenquiry',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='status',
            new_name='Status',
        ),
    ]
