# Generated by Django 4.2.2 on 2023-06-14 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapp', '0031_rename_comments_enquiry_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='last_insert',
            new_name='last_updated',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AddField(
            model_name='todo',
            name='assign_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='restapp.users'),
        ),
        migrations.AddField(
            model_name='todo',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='todo',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todo',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('review', 'Review'), ('inprogress', 'In Progress')], default='inprogress', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='team',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
