# Generated by Django 4.2.2 on 2023-06-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0032_rename_last_insert_todo_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
