# Generated by Django 4.2.2 on 2023-06-15 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0033_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_user',
            name='findDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
