# Generated by Django 4.2.2 on 2023-06-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0037_alter_comment_user_finddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_user',
            name='findDate',
            field=models.TextField(),
        ),
    ]
