# Generated by Django 4.2.2 on 2023-06-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0038_alter_comment_user_finddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='comments',
            field=models.ManyToManyField(related_name='tasks', to='restapp.comment'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
