# Generated by Django 4.1.7 on 2023-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0039_users_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
