# Generated by Django 4.1.7 on 2023-06-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0040_alter_users_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='verification_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
