<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-16 11:37
=======
# Generated by Django 4.1.7 on 2023-06-16 11:18
>>>>>>> 4b7a6bd231782667936bc0faa45f61566d79b60f

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0042_mu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mu',
        ),
        migrations.RemoveField(
            model_name='comment_user',
            name='task',
        ),
    ]
