# Generated by Django 4.2.2 on 2023-06-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0043_delete_mu_remove_comment_user_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_user',
            name='task',
            field=models.TextField(null=True),
        ),
    ]
