# Generated by Django 4.2.2 on 2023-06-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0047_rename_customuser_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
