# Generated by Django 4.2.2 on 2023-06-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0049_alter_comment_receiver_id_alter_comment_sender_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Officevisit',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
