# Generated by Django 4.2.2 on 2023-06-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0050_alter_enquiry_officevisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
