# Generated by Django 4.2.2 on 2023-06-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0053_alter_todo_status_todocomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_user',
            name='findDate',
            field=models.TextField(null=True),
        ),
    ]
