# Generated by Django 4.2.2 on 2023-06-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0054_alter_comment_user_finddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='Domain',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='qa',
            name='Skills',
            field=models.JSONField(null=True),
        ),
    ]
